const ACTIONS = {
    LOAD_MOVIES_IN_PROGRESS: 'LOAD_MOVIES_IN_PROGRESS',
    LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
    LOAD_MOVIES_FAILURE: 'LOAD_MOVIES_FAILURE',
    SET_ADD_MODAL_VISIBILITY: 'SET_ADD_MODAL_VISIBILITY',
    SELECT_MOVIE: 'SELECT_MOVIE',
    DESELECT_MOVIE: 'DESELECT_MOVIE',
    SET_FILTER: 'SET_FILTER',
    SET_SORT: 'SET_SORT' 
};

export default ACTIONS;