const ACTIONS = {
    LOAD_MOVIES_IN_PROGRESS: 'LOAD_MOVIES_IN_PROGRESS',
    LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
    LOAD_MOVIES_FAILURE: 'LOAD_MOVIES_FAILURE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    ADD_MOVIE: 'ADD_MOVIE',
    MOVIES_CHANGED: 'MOVIES_CHANGED',
    SET_FILTER: 'SET_FILTER',
    SET_SORT: 'SET_SORT' ,
    MOVIE_VALUE_CHANGED: 'MOVIE_VALUE_CHANGED', 
    RESET_MOVIE: 'RESET_MOVIE',

    SET_ADD_MODAL_VISIBILITY: 'SET_ADD_MODAL_VISIBILITY',
    SET_EDIT_MODAL_VISIBILITY: 'SET_EDIT_MODAL_VISIBILITY',
    SET_DELETE_MODAL_VISIBILITY: 'SET_DELETE_MODAL_VISIBILITY',
    SELECT_MOVIE: 'SELECT_MOVIE',
    DESELECT_MOVIE: 'DESELECT_MOVIE',
    SHOW_OPTIONS: 'SHOW_OPTIONS',
    HIDE_OPTIONS: 'HIDE_OPTIONS',
};

export default ACTIONS;